### Heroes Of Pymoli Data Analysis
* Of the 1163 active players, the vast majority are male (84%). There also exists, a smaller, but notable proportion of female players (14%).

* Our peak age demographic falls between 20-24 (44.8%) with secondary groups falling between 15-19 (18.60%) and 25-29 (13.4%).  
-----

### Note
* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [152]:
# Dependencies and Setup
import pandas as pd
import numpy as np

# File to Load (Remember to Change These)
file_to_load = "Resources/purchase_data.csv"

# Read Purchasing File and store into Pandas data frame
purchase_data = pd.read_csv(file_to_load)

#rename columns
purchase_data=purchase_data.rename(columns={"Purchase ID":"Purchase_ID", "Item ID":"Item_ID", "Item Name":"Item_Name"})
purchase_data.head()
#purchase_data.describe(include = "all")

,Purchase_ID,SN,Age,Gender,Item_ID,Item_Name,Price
0,0,Lisim78,20,Male,108,"Extraction, Quickblade Of Trembling Hands",3.53
1,1,Lisovynya38,40,Male,143,Frenzied Scimitar,1.56
2,2,Ithergue48,24,Male,92,Final Critic,4.88
3,3,Chamassasya86,24,Male,100,Blindscythe,3.27
4,4,Iskosia90,23,Male,131,Fury,1.44

## Player Count

* Display the total number of players

In [153]:
#SN is unique per user. created an array of unique names in SN

unique_player = purchase_data["SN"].unique()

#The lenth of array is the total of unique players
number_of_unique_palyers = len(unique_player)

In [154]:
data = [number_of_unique_palyers]
pd.DataFrame(data, columns=["Total Players"])

   Total Players
0            576

## Purchasing Analysis (Total)

* Run basic calculations to obtain number of unique items, average price, etc.


* Create a summary data frame to hold the results


* Optional: give the displayed data cleaner formatting


* Display the summary data frame

In [155]:
#create a series of unique item IDs and get the length to calculate unique items

unique_items = purchase_data["Item_ID"].unique()


#Use mean function on "Price" per purchase to calcualte average price

average_purchase_price = purchase_data["Price"].mean()

#Total purchases is the number of entries/rows. I used purchased ID column.

purchases = purchase_data["Purchase_ID"]

#The total profit is the sum of all transactions.

Total_revenue = purchase_data["Price"].sum()

In [156]:
#Output data on new DataFrame

data = [[len(unique_items), average_purchase_price, len(purchases), Total_revenue]]
pd.DataFrame(data, columns=["Number of Unique Items", "Average Price","Number of purchases", "Total Revenue"])

   Number of Unique Items  Average Price  Number of purchases  Total Revenue
0                     183       3.050987                  780        2379.77

## Gender Demographics

* Percentage and Count of Male Players


* Percentage and Count of Female Players


* Percentage and Count of Other / Non-Disclosed

In [157]:
#create a new dataframe with rows of repeated users dropped.
minus_duplicated_df = purchase_data.drop_duplicates(['SN'])

#From this new dataframe count the occurrences of each gender
genders = minus_duplicated_df["Gender"].value_counts()

male_users = genders[0]
percent_male = (male_users*100)/number_of_unique_palyers
female_users = genders[1]
percent_female = (female_users*100)/number_of_unique_palyers
na_users = genders[2]
percent_na = (na_users*100)/number_of_unique_palyers

In [158]:
# Place all of the data found into a summary DataFrame

gender_demographics = pd.DataFrame({
    "": ["Male", "Female", "Other / Non-disclosed"],
    "Total Counts": [male_users, female_users, na_users],
    "Percentage of Players": [percent_male, percent_female, percent_na]
})
gender_demographics

                          Total Counts  Percentage of Players
0                   Male           484              84.027778
1                 Female            81              14.062500
2  Other / Non-disclosed            11               1.909722


## Purchasing Analysis (Gender)

* Run basic calculations to obtain purchase count, avg. purchase price, avg. purchase total per person etc. by gender




* Create a summary data frame to hold the results


* Optional: give the displayed data cleaner formatting


* Display the summary data frame

In [198]:
purchase_data.groupby('Gender').Purchase_ID.count()

Gender
Female                   113
Male                     652
Other / Non-Disclosed     15
Name: Purchase_ID, dtype: int64

In [195]:
purchase_data.groupby('Gender').Price.mean()

Gender
Female                   3.203009
Male                     3.017853
Other / Non-Disclosed    3.346000
Name: Price, dtype: float64

In [185]:
purchase_data.groupby('Gender').Price.sum()

Gender
Female                    361.94
Male                     1967.64
Other / Non-Disclosed      50.19
Name: Price, dtype: float64

In [218]:
#Filtered and created separate dataframes per gender

male_df = purchase_data[purchase_data['Gender']=="Male"]

female_df = purchase_data[purchase_data['Gender']=="Female"]

na_df = purchase_data[purchase_data['Gender']=="Other / Non-Disclosed"]

female_df

,Purchase_ID,SN,Age,Gender,Item_ID,Item_Name,Price
15,15,Lisassa64,21,Female,98,"Deadline, Voice Of Subtlety",2.89
18,18,Reunasu60,22,Female,82,Nirvana,4.90
38,38,Reulae52,10,Female,116,Renewed Skeletal Katana,4.18
41,41,Assosia88,20,Female,7,"Thorn, Satchel of Dark Souls",1.33
55,55,Phaelap26,25,Female,84,Arcane Gem,3.79
66,66,Chanastsda67,21,Female,6,Rusty Skull,3.70
71,71,Hari50,20,Female,29,"Chaos, Ender of the End",1.98
72,72,Marilsa69,25,Female,178,"Oathbreaker, Last Hope of the Breaking Storm",4.23
76,76,Mindadaran26,13,Female,88,"Emberling, Defender of Delusions",3.75
81,81,Heudai45,8,Female,174,Primitive Blade,3.47
84,84,Jiskjask60,21,Female,34,Retribution Axe,2.22
85,85,Umolrian85,32,Female,33,Curved Axe,1.16
92,92,Chadistaya75,21,Female,39,"Betrayal, Whisper of Grieving Widows",3.94
112,112,Iskichinya81,21,Female,7,"Thorn, Satchel of Dark Souls",1.33
113,113,Phyali88,15,Female,140,Striker,2.94
117,117,Frichaststa61,21,Female,117,"Heartstriker, Legacy of the Light",1.79
119,119,Frichosia58,15,Female,87,"Deluge, Edge of the West",4.43
125,125,Yathecal82,20,Female,62,Piece Maker,1.87
134,134,Phyali88,15,Female,2,Verdict,2.48
140,140,Hari50,20,Female,8,"Purgatory, Gem of Regret",3.93
142,142,Adastirin33,35,Female,175,Woeful Adamantite Claymore,4.48
155,155,Aillyrin83,10,Female,98,"Deadline, Voice Of Subtlety",2.89
157,157,Marast30,18,Female,108,"Extraction, Quickblade Of Trembling Hands",3.53
166,166,Sondim68,22,Female,30,Stormcaller,2.21
169,169,Heosurnuru52,16,Female,123,Twilight's Carver,2.28
177,177,Syathe73,30,Female,135,Warped Diamond Crusader,1.40
178,178,Baelollodeu94,20,Female,57,"Despair, Favor of Due Diligence",4.60
196,196,Maradaran90,35,Female,9,"Thorn, Conqueror of the Corrupted",2.73
199,199,Ialallo29,15,Female,138,"Peacekeeper, Wit of Dark Magic",4.74
206,206,Haisurra41,20,Female,78,"Glimmer, Ender of the Moon",4.40
...,...,...,...,...,...,...,...
555,555,Pheosurllorin41,23,Female,7,"Thorn, Satchel of Dark Souls",1.33
558,558,Lassadarsda57,25,Female,108,"Extraction, Quickblade Of Trembling Hands",3.53
564,564,Chamjask73,22,Female,52,Hatred,4.84
569,569,Baelollodeu94,20,Female,87,"Deluge, Edge of the West",4.43
572,572,Yoishirrala98,17,Female,145,Fiery Glass Crusader,4.58
578,578,Aerithllora36,29,Female,153,Mercenary Sabre,3.74
579,579,Marilsa69,25,Female,12,Dawne,1.02
586,586,Chanirra79,23,Female,155,War-Forged Gold Deflector,1.01
588,588,Lassadarsda57,25,Female,15,Soul Infused Crystal,2.96
607,607,Rithe53,15,Female,80,Dreamsong,3.39
608,608,Leyirra83,24,Female,132,Persuasion,3.33
613,613,Quanrion96,21,Female,159,"Oathbreaker, Spellblade of Trials",3.08
615,615,Sida61,20,Female,72,Winter's Bite,3.77
618,618,Aisurdru79,29,Female,183,Dragon's Greatsword,1.09
641,641,Lisirra58,20,Female,49,"The Oculus, Token of Lost Worlds",2.96
653,653,Chamast86,32,Female,53,Vengeance Cleaver,2.05
658,658,Quilassa66,7,Female,178,"Oathbreaker, Last Hope of the Breaking Storm",4.23
666,666,Assilsan72,20,Female,82,Nirvana,4.90
667,667,Inasuir29,40,Female,66,Victor Iron Spikes,4.40
683,683,Ialallo29,15,Female,145,Fiery Glass Crusader,4.58
697,697,Tyaelistidru84,19,Female,1,Crucifer,3.26
698,698,Yarithrin84,30,Female,58,"Freak's Bite, Favor of Holy Might",4.14
699,699,Tyaelly53,17,Female,130,Alpha,2.07
714,714,Tyidaim51,16,Female,103,Singed Scalpel,4.35
727,727,Yathecal82,20,Female,104,Gladiator's Glaive,1.93
731,731,Eudanu84,22,Female,12,Dawne,1.02
740,740,Reunasu60,22,Female,127,"Heartseeker, Reaver of Souls",3.92
754,754,Pheosurllorin41,23,Female,79,"Alpha, Oath of Zeal",4.05
767,767,Ilmol66,8,Female,92,Final Critic,4.88
775,775,Aethedru70,21,Female,60,Wolf,3.54

In [217]:
#Find total purchases per gender
all_purchases = purchase_data["Gender"].value_counts()

all_male_purchases = all_purchases[1]
all_female_purchases = all_purchases[0]
all_na_purchases = all_purchases[2]

#Use groupby and mean to get average purchase by gender

average_male_purchase = purchase_data.groupby('Gender').Price.mean()[1]
average_female_purchase = purchase_data.groupby('Gender').Price.mean()[0]
average_na_purchase = purchase_data.groupby('Gender').Price.mean()[2]

#Use groupny and sum to get total purchase by gender

total_male_purchase = purchase_data.groupby('Gender').Price.sum()[1]
total_female_purchase = purchase_data.groupby('Gender').Price.sum()[0]
total_na_purchase = purchase_data.groupby('Gender').Price.sum()[2]

#
total_female_purchase_peruser = female_df.groupby('SN').Price.sum()[0]
total_male_purchase_peruser = male_df.groupby('SN').Price.sum()[1]
total_na_purchase_peruser = na_df.groupby('SN').Price.sum()[2]

print(total_female_purchase_peruser,total_male_purchase_peruser,total_na_purchase_peruser)

print(all_female_purchases,average_female_purchase,total_female_purchase)
print(all_male_purchases,average_male_purchase,total_male_purchase)
print(all_na_purchases,average_na_purchase,total_na_purchase)

4.48 4.91 3.94
652 3.203008849557519 361.93999999999966
113 3.0178527607361953 1967.6399999999994
15 3.3460000000000005 50.190000000000005

## Age Demographics

* Establish bins for ages


* Categorize the existing players using the age bins. Hint: use pd.cut()


* Calculate the numbers and percentages by age group


* Create a summary data frame to hold the results


* Optional: round the percentage column to two decimal points


* Display Age Demographics Table

## Purchasing Analysis (Age)

* Bin the purchase_data data frame by age


* Run basic calculations to obtain purchase count, avg. purchase price, avg. purchase total per person etc. in the table below


* Create a summary data frame to hold the results


* Optional: give the displayed data cleaner formatting


* Display the summary data frame

## Top Spenders

* Run basic calculations to obtain the results in the table below


* Create a summary data frame to hold the results


* Sort the total purchase value column in descending order


* Optional: give the displayed data cleaner formatting


* Display a preview of the summary data frame

## Most Popular Items

* Retrieve the Item ID, Item Name, and Item Price columns


* Group by Item ID and Item Name. Perform calculations to obtain purchase count, item price, and total purchase value


* Create a summary data frame to hold the results


* Sort the purchase count column in descending order


* Optional: give the displayed data cleaner formatting


* Display a preview of the summary data frame

## Most Profitable Items

* Sort the above table by total purchase value in descending order


* Optional: give the displayed data cleaner formatting


* Display a preview of the data frame